import { useState, useRef, useEffect } from 'react';
import { isTauri } from '../../lib/tauri-commands';
import { useNotify } from '../../contexts/ToastContext';
import type { AnalysisTab } from '../../types';

interface ExportButtonProps {
  tab?: AnalysisTab;
  onExport?: (format: 'pdf' | 'csv' | 'json') => void | Promise<void>;
  disabled?: boolean;
}

function getExportContent(tab: AnalysisTab, format: 'csv' | 'json'): string {
  const result = tab.result as unknown as Record<string, unknown> | undefined;
  if (format === 'json') {
    return JSON.stringify({ address: tab.address, chain: tab.chain, result, transactions: tab.transactions, funding: tab.fundingData }, null, 2);
  }
  // CSV
  const txs = tab.transactions as unknown as Record<string, unknown> | undefined;
  const txList = (txs?.transactions || txs?.data || txs?.result || []) as Array<Record<string, unknown>>;
  if (!txList.length) return 'hash,from,to,value,timestamp\nNo transaction data';
  const headers = ['hash', 'from', 'to', 'value', 'timestamp'];
  const rows = txList.map((tx: Record<string, unknown>) =>
    headers.map(h => tx[h] || tx[h.replace(/[A-Z]/g, '_$&').toLowerCase()] || '').join(',')
  );
  return [headers.join(','), ...rows].join('\n');
}

async function generatePDF(tab: AnalysisTab): Promise<Blob> {
  const jspdf: any = await import('jspdf');
  const jsPDF = jspdf.default || jspdf.jsPDF;
  const jspdfAutotable: any = await import('jspdf-autotable');
  const autoTable = jspdfAutotable.default;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Title
  doc.setFontSize(18);
  doc.text('FundTracer Report', 14, 20);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Address: ${tab.address}`, 14, 30);
  doc.text(`Chain: ${tab.chain.toUpperCase()}`, 14, 37);
  doc.text(`Generated: ${new Date().toISOString().slice(0, 19)}`, 14, 44);

  // Transactions table
  const txs = tab.transactions as unknown as Record<string, unknown> | undefined;
  const txList = (txs?.transactions || txs?.data || txs?.result || []) as Array<Record<string, unknown>>;

  if (txList.length > 0) {
    const rows = txList.map((tx: Record<string, unknown>) => [
      (tx.hash as string || '').slice(0, 14) + '...',
      (tx.from as string || '').slice(0, 14) + '...',
      (tx.to as string || '').slice(0, 14) + '...',
      tx.value || tx.value_usd || '',
      tx.timestamp || '',
    ]);

    autoTable(doc, {
      head: [['Hash', 'From', 'To', 'Value', 'Timestamp']],
      body: rows,
      startY: 52,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by FundTracer · fundtracer.xyz', 14, doc.internal.pageSize.height - 10);
  }

  return doc.output('blob');
}

export function ExportButton({ tab, onExport, disabled }: ExportButtonProps) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const notify = useNotify();

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const handleExport = async (format: 'pdf' | 'csv' | 'json') => {
    setOpen(false);
    try {
      if (onExport) {
        await onExport(format);
        notify.success(`Exported as ${format.toUpperCase()}`);
        return;
      }

      if (!tab) return;

      if (format === 'pdf') {
        const blob = await generatePDF(tab);

        // Try Tauri save dialog
        if (isTauri()) {
          try {
            const { save } = await import('@tauri-apps/plugin-dialog');
            const { writeFile } = await import('@tauri-apps/plugin-fs');
            const filePath = await save({
              defaultPath: 'fundtracer-report.pdf',
              filters: [{ name: 'PDF', extensions: ['pdf'] }],
            });
            if (filePath) {
              const buf = await blob.arrayBuffer();
              await writeFile(filePath, new Uint8Array(buf));
              notify.success('PDF exported');
            }
            return;
          } catch { /* fall through to browser download */ }
        }

        // Browser fallback
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'fundtracer-report.pdf';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        notify.success('PDF exported');
        return;
      }

      // CSV or JSON — text-based
      const content = getExportContent(tab, format);
      const mimeTypes: Record<string, string> = {
        csv: 'text/csv',
        json: 'application/json',
      };
      const exts: Record<string, string> = {
        csv: 'csv', json: 'json',
      };

      if (isTauri()) {
        try {
          const { save } = await import('@tauri-apps/plugin-dialog');
          const { writeTextFile } = await import('@tauri-apps/plugin-fs');
          const filePath = await save({
            defaultPath: `fundtracer-report.${exts[format]}`,
            filters: [{ name: format.toUpperCase(), extensions: [exts[format]] }],
          });
          if (filePath) {
            await writeTextFile(filePath, content);
            notify.success(`Exported as ${format.toUpperCase()}`);
          }
          return;
        } catch { /* fall through */ }
      }

      const blob = new Blob([content], { type: mimeTypes[format] });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `fundtracer-report.${exts[format]}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      notify.success(`Exported as ${format.toUpperCase()}`);
    } catch (err) {
      if (err !== 'cancelled') {
        notify.error('Export failed');
      }
    }
  };

  return (
    <div ref={ref} style={{ position: 'relative' }}>
      <button
        onClick={() => setOpen(!open)}
        disabled={disabled}
        style={{
          padding: '6px 14px',
          borderRadius: 'var(--radius-md)',
          border: '1px solid var(--card-border)',
          background: 'var(--card)',
          color: disabled ? 'var(--fg-tertiary)' : 'var(--fg)',
          fontSize: 12,
          fontFamily: 'var(--font-sans)',
          cursor: disabled ? 'default' : 'pointer',
          display: 'flex',
          alignItems: 'center',
          gap: 6,
        }}
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
        </svg>
        Export
      </button>

      {open && (
        <div style={{
          position: 'absolute',
          right: 0,
          top: '100%',
          marginTop: 4,
          background: 'var(--bg-secondary)',
          border: '1px solid var(--card-border)',
          borderRadius: 'var(--radius-lg)',
          boxShadow: 'var(--shadow-overlay)',
          overflow: 'hidden',
          zIndex: 200,
          minWidth: 160,
        }}>
          {[
            { format: 'pdf' as const, label: 'PDF Report', desc: 'Formatted document with tables' },
            { format: 'csv' as const, label: 'CSV Data', desc: 'Spreadsheet-ready transaction data' },
            { format: 'json' as const, label: 'JSON Raw', desc: 'Machine-readable full data dump' },
          ].map(item => (
            <button
              key={item.format}
              onClick={() => handleExport(item.format)}
              style={{
                display: 'block',
                width: '100%',
                padding: '10px 16px',
                border: 'none',
                background: 'transparent',
                color: 'var(--fg)',
                fontSize: 12,
                fontFamily: 'var(--font-sans)',
                textAlign: 'left',
                cursor: 'pointer',
              }}
              onMouseEnter={e => { e.currentTarget.style.background = 'var(--hover-overlay)'; }}
              onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; }}
            >
              <div style={{ fontWeight: 600 }}>{item.label}</div>
              <div style={{ fontSize: 10, color: 'var(--fg-tertiary)', marginTop: 1 }}>{item.desc}</div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
