[build]
  command = "npm run build"
  publish = "packages/web/dist"

[[redirects]]
  from = "/api/*"
  to = "https://fundtracer-by-dt-production.up.railway.app/api/:splat"
  status = 307
  force = true
